apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-install
spec:
  selector:
    matchLabels:
      app: docker-install
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-install
    spec:
      containers:
      - name: docker
        image: docker:latest
        command: ["/bin/sh", "-c"]
        args:
          - curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
      restartPolicy: Never
